### PR TITLE
added z-score analysis to anomalies

### PR DESCRIPTION
**Pull request by lokeshwarlakhi**
Added z-score analysis by taking data integrity as base.

fixes https://github.com/uptrain-ai/uptrain/issues/101

### CODE REVIEW

**Comment by vipgupta** [comment]
Hi @lokeshwarlakhi , the commit looks good to me. Thanks for adding the example. Can you also add a test file on how to use z-score to [this folder](https://github.com/uptrain-ai/uptrain/tree/main/uptrain/tests) (the name can be test_zscore.py)? That way, I can understand how it is used, and in the future, we can use it to check whether z-score test is running successfully with new changes.

**Comment by vipgupta** [comment]
A better way to add z-score:

Add a condition to this line for a z-score test: https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/data_integrity.py#L28

It would be like the following we did for concept drift (and added a DDM algorithm): https://github.com/uptrain-ai/uptrain/blob/main/uptrain/core/classes/anomalies/concept_drift.py#L23

**Comment by lokeshwarlakhi** [comment]
Hey @vipgupta , I've made the changes you requested. Just see if it works 🤞🏾. Please let me know if there are any changes that need to be made. 
- [x] Added test file for z_score
- [x] integrated z_score in data_integrity.py

**Comment by Dominastorm** [comment]
Hey @lokeshwarlakhi, thanks for your contribution. We used quite a bit of your code for implementing the z-score feature in #212. This PR can be closed now.

**Comment by vipgupta** [comment]
This feature is now added

**Pull request closed without merging**
